### ISSUE TITLE
Possible missing items

### ISSUE THREAD

**Issue by mfeingesicht** [cr4ckp0t/AdiBags_KorthianRelics#1]
Hi,

You might want to add the following items to the "Korthian items" filter :

- Zovaal's Dark Carafe - 187236
- Collapsing Riftstone - 186969
- Tasty Mawshroom - 187153
- Ashen Liniment - 187421
- Trained Gromit Carrier - 187508
- Korthite Crystal - 186017 (not sure about this one, it's kind of a legendary crafting material)

Thanks !

**Comment by cr4ckp0t** [comment]
I added them all, except Korthite Crystal, because it is considered a tradeskill item.
